name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
    
  with:
    output_location: "dist"
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    action: "upload"
    app_location: "/"          
    api_location: ""           

 name: Ensure vite is executable

  - name: Install dependencies
  run: npm ci

- name: Ensure vite is executable
  run: chmod +x node_modules/.bin/vite

- name: Build
  run: npm run build




